### ISSUE TITLE
Error during loaddata: value too long for type character varying(63)

### ISSUE THREAD

**Issue by jayvdb** [raratiru/django-quenv#13]
DataError

> Problem installing fixture '....json': Could not load quenv.License(pk=None): value too long for type character varying(63)

I'll have to get the file off the server to work out what part of the json failed.

**Comment by raratiru** [comment]
OK, I am increasing the `max_length`.

**Comment by raratiru** [comment]
I have increased the `max_length`s.

Could you migrate and check? Is it a huge title or a bug?

**Comment by jayvdb** [comment]
Irrespective of whether that minor increase of the max helps my case (I am 90% sure it wont), it is not sufficient as a general solution.

I have seen packages which read all of README.md into the title, and all of LICENSE into the license field.  Some really good software have really bad `setup.py`, because most devs dont see or care what happens in PKG-INFO.  Trimming is needed, and/or replacing unacceptable values with placeholders.

**Comment by raratiru** [comment]
> I have seen packages which read all of README.md into the title, and all of LICENSE into the license field. Some really good software have really bad `setup.py`, because most devs dont see or care what happens in PKG-INFO. Trimming is needed, and/or replacing unacceptable values with placeholders.

Shocking!

I have released `0.1.6` where I try to trim those cases:

https://github.com/raratiru/django-quenv/blob/7a900e3d73de4cb9477375f3257eef99f9126eb0/quenv/licenses.py#L163-L175

I have also diminished admin renaming the remaining useful tables. Hence the new migration, which makes me think that I should have versioned it like `0.2.0`. 

Could you please check if it works?

**Comment by jayvdb** [comment]
This problem is now resolved.
