### ISSUE TITLE
Version change trigger

### ISSUE THREAD

**Issue by jayvdb** [raratiru/django-quenv#17]
Hiya, I have an issue https://github.com/morlandi/django-tables-cleaner/issues/6 I am looking to solve requiring a event trigger when starting django on a different version of Django

Naturally, this app came to mind.  There may not even be a need to make large changes here.  If there is a startup version check, and the model is updated, the model change could be the trigger using something like https://github.com/omni-digital/django-conditioner (probably not py3/dj2-3 compatible yet) or https://github.com/adamhaney/django-dynamic-business-rules (see my PR there if trying to use this).

**Comment by raratiru** [comment]
Django-quenv, caters for different python environments, could this be of help?
